services:
  db:
    image: postgres:16
    container_name: mana-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mana_db
    ports:
      - '5432:5432'
    volumes:
      - mana_pgdata:/var/lib/postgresql/data

volumes:
  mana_pgdata:
